# Code generated by GenAI.

from django.db import models

class Order(models.Model):
    """
    The high-level summary of the transaction.
    Contains data that applies to the entire purchase.
    """
    invoice_no = models.CharField(
        max_length=50, 
        unique=True,
        help_text="The unique invoice number identifying this specific order."
    ) 
    customer_id = models.CharField(
        max_length=50, 
        null=True, 
        blank=True,
        help_text="The unique identifier for the customer who placed the order."
    )
    invoice_date = models.DateTimeField(
        help_text="The exact date and time the order was placed."
    )
    country = models.CharField(
        max_length=100, 
        default="United Kingdom",
        help_text="The country where the order was placed or shipped."
    )
    order_status = models.CharField(
        max_length=50, 
        default='Pending',
        help_text="The current processing status of the order (e.g., Pending, Shipped)."
    )

    class Meta:
        ordering = ['-invoice_date']

    def __str__(self):
        return f"Order {self.invoice_no} (Customer: {self.customer_id})"

    @property
    def total_value(self):
        """Dynamically calculates the total price of all items in this order."""
        return sum(item.line_total for item in self.items.all())

    @property
    def total_items_count(self):
        """Dynamically calculates the total physical quantity of items."""
        return sum(item.quantity for item in self.items.all())


class OrderItem(models.Model):
    """
    An individual line item belonging to a specific Order.
    """
    order = models.ForeignKey(
        Order, 
        related_name='items', 
        on_delete=models.CASCADE,
        help_text="The parent order this item belongs to."
    )
    
    stock_code = models.CharField(
        max_length=50,
        help_text="The unique stock keeping unit (SKU) or product code."
    )
    description = models.CharField(
        max_length=255, 
        null=True, 
        blank=True,
        help_text="A brief text description of the product."
    )
    quantity = models.IntegerField(
        help_text="The number of units purchased for this specific item."
    )
    price = models.DecimalField(
        max_digits=10, 
        decimal_places=2,
        help_text="The price per single unit of this item."
    )

    def __str__(self):
        return f"{self.quantity}x {self.stock_code} for Order {self.order.invoice_no}"

    @property
    def line_total(self):
        """Calculates the price for this specific row."""
        return self.quantity * self.price