# Code generated by GenAI.

from rest_framework import serializers
from .models import Order, OrderItem

class OrderItemSerializer(serializers.ModelSerializer):
    # Include the calculated property as a read-only field
    line_total = serializers.ReadOnlyField()

    class Meta:
        model = OrderItem
        fields = ['id', 'stock_code', 'description', 'quantity', 'price', 'line_total']

class OrderSerializer(serializers.ModelSerializer):
    # REMOVED read_only=True so we can receive items in a POST request
    items = OrderItemSerializer(many=True)
    
    total_value = serializers.ReadOnlyField()
    total_items_count = serializers.ReadOnlyField()

    class Meta:
        model = Order
        fields = [
            'invoice_no', 'customer_id', 'invoice_date', 'country', 
            'order_status', 'total_value', 'total_items_count', 'items'
        ]

    def create(self, validated_data):
        # 1. 'Pop' (extract and remove) the items array from the validated data
        items_data = validated_data.pop('items', [])
        
        # 2. Create the parent Order with the remaining data
        order = Order.objects.create(**validated_data)
        
        # 3. Loop through the items array and create the child OrderItems linked to the new order
        for item_data in items_data:
            OrderItem.objects.create(order=order, **item_data)
            
        return order