# Code generated by GenAI.

from django.shortcuts import render
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import status
from .models import Order, OrderItem
from .serializers import OrderSerializer
from django.db.models import Count, Sum, F
from datetime import datetime

# Create your views here.

# Handles Create (POST) and Read All (GET)
@api_view(['GET', 'POST'])
def order_list(request):
    if request.method == 'GET':
        orders = Order.objects.all()
        serializer = OrderSerializer(orders, many=True)
        return Response(serializer.data) # Returns 200 OK
    
    elif request.method == 'POST':
        serializer = OrderSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

# Handles Read One (GET), Update (PATCH), and Delete (DELETE)
@api_view(['GET', 'PATCH', 'DELETE'])
def order_detail(request, pk):
    try:
        order = Order.objects.get(invoice_no=pk)
    except Order.DoesNotExist:
        return Response({'error': 'Order not found'}, status=status.HTTP_404_NOT_FOUND)

    if request.method == 'GET':
        serializer = OrderSerializer(order)
        return Response(serializer.data)

    elif request.method == 'PATCH':
        # partial=True allows us to just update one field, like 'order_status'
        serializer = OrderSerializer(order, data=request.data, partial=True)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    elif request.method == 'DELETE':
        order.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

@api_view(['GET'])
def order_analytics(request):
    """Updated basic analytics for the new schema."""
    total_orders = Order.objects.count()
    status_counts = Order.objects.values('order_status').annotate(count=Count('order_status'))
    status_breakdown = {item['order_status']: item['count'] for item in status_counts}

    # FIX: Calculate items by looking across the ForeignKey relationship to OrderItem
    items_in_store = OrderItem.objects.filter(
        order__order_status__in=['Pending', 'Ready for Collection']
    ).aggregate(total_physical_items=Sum('quantity'))['total_physical_items'] or 0

    return Response({
        "metrics": {
            "total_orders_tracked": total_orders,
            "physical_items_in_stockroom": items_in_store
        },
        "status_breakdown": status_breakdown
    })

@api_view(['GET'])
def advanced_analytics(request):
    """
    High-level database aggregation demonstrating advanced SQL/ORM queries.
    """
    # 1. Total Revenue across the entire store (Quantity * Price for all items)
    total_revenue = OrderItem.objects.aggregate(
        revenue=Sum(F('quantity') * F('price'))
    )['revenue'] or 0

    # 2. Top 5 Best-Selling Products
    top_products = OrderItem.objects.values('stock_code', 'description').annotate(
        total_sold=Sum('quantity')
    ).order_by('-total_sold')[:5]

    # 3. Orders by Country Distribution
    country_breakdown = Order.objects.values('country').annotate(
        order_count=Count('invoice_no')
    ).order_by('-order_count')

    return Response({
        "total_revenue": round(total_revenue, 2),
        "top_5_products": list(top_products),
        "country_distribution": list(country_breakdown)
    })

@api_view(['GET'])
def customer_orders(request, customer_id):
    # Returns all orders associated with a specific Customer ID.

    orders = Order.objects.filter(customer_id=customer_id)

    # Return error code 404 if the customer has no orders.
    if not orders.exists():
        return Response({'message': 'No orders found for this customer.'}, status=status.HTTP_404_NOT_FOUND)
    
    serializer = OrderSerializer(orders, many=True)
    return Response(serializer.data)

@api_view(['GET'])
def large_orders(request):
    """
    Returns orders that have a high number of items. 
    Defaults to 20+, but allows a custom threshold via URL query (?threshold=X).
    """
    threshold = request.GET.get('threshold', 20)
    
    try:
        threshold = int(threshold)
    except ValueError:
        return Response({'error': 'Threshold must be a valid number.'}, status=400)

    # FIX: Dynamically calculate the sum of the nested items' quantities, THEN filter!
    orders = Order.objects.annotate(
        calculated_total=Sum('items__quantity')
    ).filter(calculated_total__gte=threshold)
    
    serializer = OrderSerializer(orders, many=True)
    return Response(serializer.data)

@api_view(['GET'])
def orders_by_date(request, date_str):
    # Returns all orders palced on a specific date (Format: YYYY-MM-DD).

    try:
        # Validate that the user provided a correctly formatted date string.
        target_data = datetime.strptime(date_str, '%Y-%m-%d').date()
    except ValueError:
        return Response({'error': 'Invalid date format. Please use YYYY-MM-DD.'}, status=status.HTTP_400_BAD_REQUEST)
    
    # Django's __date lookup extracts just the date part from the DateTimeField.
    orders = Order.objects.filter(invoice_date__date=target_data)
    serializer = OrderSerializer(orders, many=True)
    return Response(serializer.data)

def dashboard(request):
    return render(request, 'orders/index.html')
    