# Code generated by GenAI.

from django.shortcuts import render
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import status
from .models import Order, OrderItem
from .serializers import OrderSerializer
from django.db.models import Count, Sum, F
from datetime import datetime
from drf_spectacular.utils import extend_schema, OpenApiParameter, OpenApiExample, OpenApiResponse
from drf_spectacular.types import OpenApiTypes

# Create your views here.

# Handles Create (POST) and Read All (GET)
@extend_schema(
    methods=['GET'],
    summary="List all Orders",
    description="Retrieve a list of all orders in the system.",
    responses={200: OrderSerializer(many=True)}
)
@extend_schema(
    methods=['POST'],
    summary="Create a New Order",
    description="Create a new order along with its nested line items.",
    examples=[
        OpenApiExample(
            "New Order Request Example",
            value={
                "invoice_no": "536367",
                "customer_id": "12345",
                "invoice_date": "2026-03-13T14:30:00Z",
                "country": "United Kingdom",
                "items": [
                    {
                        "stock_code": "84879",
                        "description": "ASSORTED COLOUR BIRD ORNAMENT",
                        "quantity": 8,
                        "price": "1.69"
                    }
                ]
            },
            request_only=True # This tells Swagger this is what the user *sends*
        )
    ],
    responses={
        201: OpenApiResponse(
            response=OrderSerializer,
            description="Order successfully created.",
            examples=[
                OpenApiExample(
                    "Created Order Response",
                    value={
                        "invoice_no": "536367",
                        "customer_id": "12345",
                        "invoice_date": "2026-03-13T14:30:00Z",
                        "country": "United Kingdom",
                        "order_status": "Pending",
                        "total_value": 13.52,
                        "total_items_count": 8,
                        "items": [
                            {
                                "stock_code": "84879",
                                "description": "ASSORTED COLOUR BIRD ORNAMENT",
                                "quantity": 8,
                                "price": "1.69",
                                "line_total": 13.52
                            }
                        ]
                    }
                )
            ]
        ),
        400: OpenApiResponse(
            description="Validation Error",
            response={
                "type": "object",
                "properties": {
                    "invoice_no": {
                        "type": "array",
                        "items": {"type": "string"},
                        "example": ["Order with this invoice no already exists."]
                    }
                }
            }
        )
    }
)
@api_view(['GET', 'POST'])
def order_list(request):
    if request.method == 'GET':
        orders = Order.objects.all()
        serializer = OrderSerializer(orders, many=True)
        return Response(serializer.data) # Returns 200 OK
    
    elif request.method == 'POST':
        serializer = OrderSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

@extend_schema(
    methods=['GET'],
    summary="Get Order Details",
    description="Fetch a specific order by its unique invoice number, including all nested line items.",
    responses={
        200: OpenApiResponse(
            response=OrderSerializer,
            description="Successful retrieval of the order.",
            examples=[
                OpenApiExample(
                    "Example Order Response",
                    value={
                        "invoice_no": "536365",
                        "customer_id": "17850",
                        "invoice_date": "2026-03-13T12:00:00Z",
                        "country": "United Kingdom",
                        "order_status": "Pending",
                        "total_value": 150.25,
                        "total_items_count": 5,
                        "items": [
                            {
                                "stock_code": "85123A",
                                "description": "WHITE HANGING HEART",
                                "quantity": 5,
                                "price": "30.05",
                                "line_total": 150.25
                            }
                        ]
                    }
                )
            ]
        ),
        404: OpenApiResponse(
            description="Order not found.",
            response={"type": "object", "properties": {"error": {"type": "string", "example": "Order not found"}}}
        )
    }
)
@extend_schema(
    methods=['PATCH'],
    summary="Update Order",
    description="Partially update an order. You only need to send the fields you want to change (e.g., updating the `order_status` to 'Shipped').",
    examples=[
        OpenApiExample(
            "Change Status Request Example",
            value={"order_status": "Shipped"},
            request_only=True
        )
    ],
    responses={
        200: OpenApiResponse(
            response=OrderSerializer,
            description="The order was successfully updated."
        ),
        400: OpenApiResponse(
            description="Bad Request (e.g., invalid data types).",
            response={"type": "object", "properties": {"order_status": {"type": "array", "items": {"type": "string"}, "example": ["Invalid status."]}}}
        ),
        404: OpenApiResponse(
            description="Order not found.",
            response={"type": "object", "properties": {"error": {"type": "string", "example": "Order not found"}}}
        )
    }
)
@extend_schema(
    methods=['DELETE'],
    summary="Delete Order",
    description="Permanently delete an order. This will also delete all associated items from the database.",
    responses={
        204: OpenApiResponse(description="Successfully deleted (No content returned)."),
        404: OpenApiResponse(
            description="Order not found.",
            response={"type": "object", "properties": {"error": {"type": "string", "example": "Order not found"}}}
        )
    }
)
@api_view(['GET', 'PATCH', 'DELETE'])
def order_detail(request, pk):
    try:
        order = Order.objects.get(invoice_no=pk)
    except Order.DoesNotExist:
        return Response({'error': 'Order not found'}, status=status.HTTP_404_NOT_FOUND)

    if request.method == 'GET':
        serializer = OrderSerializer(order)
        return Response(serializer.data)

    elif request.method == 'PATCH':
        # partial=True allows us to just update one field, like 'order_status'
        serializer = OrderSerializer(order, data=request.data, partial=True)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    elif request.method == 'DELETE':
        order.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

@extend_schema(
    summary="Basic Order Analytics",
    description="Returns total tracked orders, items in the stockroom, and a breakdown of orders by status.",
    responses={
        200: OpenApiResponse(
            response=OpenApiTypes.OBJECT,
            examples=[
                OpenApiExample(
                    'Basic Metrics', 
                    value={
                        "metrics": {"total_orders_tracked": 120, "physical_items_in_stockroom": 450},
                        "status_breakdown": {"Pending": 15, "Collected": 105}
                    }
                )
            ]
        )
    }
)
@api_view(['GET'])
def order_analytics(request):
    """Updated basic analytics for the new schema."""
    total_orders = Order.objects.count()
    status_counts = Order.objects.values('order_status').annotate(count=Count('order_status'))
    status_breakdown = {item['order_status']: item['count'] for item in status_counts}

    # FIX: Calculate items by looking across the ForeignKey relationship to OrderItem
    items_in_store = OrderItem.objects.filter(
        order__order_status__in=['Pending', 'Ready for Collection']
    ).aggregate(total_physical_items=Sum('quantity'))['total_physical_items'] or 0

    return Response({
        "metrics": {
            "total_orders_tracked": total_orders,
            "physical_items_in_stockroom": items_in_store
        },
        "status_breakdown": status_breakdown
    })

@extend_schema(
    summary="Advanced Sales Analytics",
    description="Calculates total revenue, identifies top 5 selling products, and provides country-wise distribution.",
    responses={
        200: OpenApiResponse(
            response=OpenApiTypes.OBJECT,
            description="Analytics Success",
            examples=[
                OpenApiExample(
                    'Analytics Example',
                    value={
                        "total_revenue": 15420.50,
                        "top_5_products": [{"stock_code": "85123A", "description": "WHITE HANGING HEART", "total_sold": 500}],
                        "country_distribution": [{"country": "United Kingdom", "order_count": 150}]
                    }
                )
            ]
        )
    }
)
@api_view(['GET'])
def advanced_analytics(request):
    """
    High-level database aggregation demonstrating advanced SQL/ORM queries.
    """
    # 1. Total Revenue across the entire store (Quantity * Price for all items)
    total_revenue = OrderItem.objects.aggregate(
        revenue=Sum(F('quantity') * F('price'))
    )['revenue'] or 0

    # 2. Top 5 Best-Selling Products
    top_products = OrderItem.objects.values('stock_code', 'description').annotate(
        total_sold=Sum('quantity')
    ).order_by('-total_sold')[:5]

    # 3. Orders by Country Distribution
    country_breakdown = Order.objects.values('country').annotate(
        order_count=Count('invoice_no')
    ).order_by('-order_count')

    return Response({
        "total_revenue": round(total_revenue, 2),
        "top_5_products": list(top_products),
        "country_distribution": list(country_breakdown)
    })

@extend_schema(
    summary="Orders by Customer",
    description="Retrieve a list of all orders placed by a specific Customer ID.",
    responses={
        200: OrderSerializer(many=True),
        404: OpenApiResponse(
            description="Customer not found or has no orders.",
            response={
                "type": "object",
                "properties": {
                    "message": {
                        "type": "string", 
                        "example": "No orders found for this customer."
                    }
                }
            }
        )
    }
)
@api_view(['GET'])
def customer_orders(request, customer_id):
    # Returns all orders associated with a specific Customer ID.

    orders = Order.objects.filter(customer_id=customer_id)

    # Return error code 404 if the customer has no orders.
    if not orders.exists():
        return Response({'message': 'No orders found for this customer.'}, status=status.HTTP_404_NOT_FOUND)
    
    serializer = OrderSerializer(orders, many=True)
    return Response(serializer.data)

@extend_schema(
    summary="Filter Large Orders",
    parameters=[
        OpenApiParameter(name='threshold', description='Minimum quantity of items to filter by', required=False, type=int)
    ],
    description="Returns orders where the sum of all item quantities meets or exceeds the threshold.",
    responses={200: OrderSerializer(many=True)}
)
@api_view(['GET'])
def large_orders(request):
    """
    Returns orders that have a high number of items. 
    Defaults to 20+, but allows a custom threshold via URL query (?threshold=X).
    """
    threshold = request.GET.get('threshold', 20)
    
    try:
        threshold = int(threshold)
    except ValueError:
        return Response({'error': 'Threshold must be a valid number.'}, status=400)

    # FIX: Dynamically calculate the sum of the nested items' quantities, THEN filter!
    orders = Order.objects.annotate(
        calculated_total=Sum('items__quantity')
    ).filter(calculated_total__gte=threshold)
    
    serializer = OrderSerializer(orders, many=True)
    return Response(serializer.data)

@extend_schema(
    summary="Filter Orders by Date",
    description="Retrieve all orders placed on a specific date.",
    parameters=[
        OpenApiParameter(name='date_str', location=OpenApiParameter.PATH, description='Format: YYYY-MM-DD', type=str)
    ],
    responses={
        200: OrderSerializer(many=True),
        400: OpenApiResponse(
            description="Invalid date format.",
            response={
                "type": "object",
                "properties": {
                    "error": {
                        "type": "string", 
                        "example": "Invalid date format. Please use YYYY-MM-DD."
                    }
                }
            }
        )
    }
)
@api_view(['GET'])
def orders_by_date(request, date_str):
    # Returns all orders palced on a specific date (Format: YYYY-MM-DD).

    try:
        # Validate that the user provided a correctly formatted date string.
        target_data = datetime.strptime(date_str, '%Y-%m-%d').date()
    except ValueError:
        return Response({'error': 'Invalid date format. Please use YYYY-MM-DD.'}, status=status.HTTP_400_BAD_REQUEST)
    
    # Django's __date lookup extracts just the date part from the DateTimeField.
    orders = Order.objects.filter(invoice_date__date=target_data)
    serializer = OrderSerializer(orders, many=True)
    return Response(serializer.data)

def dashboard(request):
    return render(request, 'orders/index.html')

from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([IsAuthenticated])
def locked_test_endpoint(request):
    return Response({
        "message": "Success!",
        "user": request.user.username,
        "auth_type": "You passed the security check."
    })
    