# Code generated by GenAI.

import os
import django
import pandas as pd
from django.utils.timezone import make_aware

# Setup Django environment
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'store_api.settings')
django.setup()

from orders.models import Order, OrderItem

def import_data():
    print("Loading Excel file...")
    # Loading 2000 rows to get a good sample of orders and items
    df = pd.read_excel('online_retail.xlsx', nrows=2000)
    
    # Filter out cancellations (invoices starting with 'C')
    df = df[~df['Invoice'].astype(str).str.startswith('C')]
    
    # Handle missing values to prevent database errors
    df['Description'] = df['Description'].fillna('No Description')
    df['Customer ID'] = df['Customer ID'].fillna('Guest')
    df['Country'] = df['Country'].fillna('Unknown')

    print(f"Processing {len(df)} individual item rows...")

    created_orders = {}

    for _, row in df.iterrows():
        invoice_no = str(row['Invoice'])
        
        # 1. Create the Order if we haven't already
        if invoice_no not in created_orders:
            aware_date = make_aware(row['InvoiceDate'])
            
            # get_or_create ensures we don't duplicate orders if we run the script twice
            order, created = Order.objects.get_or_create(
                invoice_no=invoice_no,
                defaults={
                    'customer_id': str(row['Customer ID']),
                    'invoice_date': aware_date,
                    'country': str(row['Country']),
                    'order_status': 'Pending' 
                }
            )
            created_orders[invoice_no] = order
        
        # 2. Create the OrderItem for this specific row
        order_instance = created_orders[invoice_no]
        
        OrderItem.objects.create(
            order=order_instance,
            stock_code=str(row['StockCode']),
            description=str(row['Description']),
            quantity=int(row['Quantity']),
            price=float(row['Price'])
        )

    print(f"Import complete! Created {len(created_orders)} unique orders and populated their items.")

if __name__ == '__main__':
    import_data()