# Generated by Django 5.2.12 on 2026-03-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('invoice_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('customer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_date', models.DateTimeField()),
                ('total_items', models.IntegerField(default=0)),
                ('order_status', models.CharField(choices=[('Pending', 'Pending'), ('Ready for Collection', 'Ready for Collection'), ('Collected', 'Collected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50)),
            ],
        ),
    ]
